openapi: 3.0.0
info:
  title: Ordering Rest API
  version: 1.0.0
  description:  Ordering Rest API 

servers:
  - url: 'http://localhost:5000'
    description: 服务端口 

components:
  schemas:
    orderDto:
      properties: 
        id:
          type: string
        totalPrice:
          type: number
        consignee:
          type: object
          properties:
            name:
              type: string
            phone:
              type: string
        orderDate:
          type: string

paths:
  /orders:
    get:
      summary: 检索订单
      description: 检索订单
      tags:
        - "orders"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/orderDto"
    post:
      summary: 创建订单
      description: 创建订单
      tags:
        - "orders"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: 
                totalPrice:
                  type: number
                consignee:
                  type: object
                  properties:
                    name:
                      type: string
                    phone:
                      type: string
                orderDate:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/orderDto"
  /orders/{id}: 
    put:
      summary: 更新订单
      description: 更新订单
      tags:
        - "orders"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: 
                id:
                  type: string
                totalPrice:
                  type: number
                consignee:
                  type: object
                  properties:
                    name:
                      type: string
                    phone:
                      type: string
                orderDate:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/orderDto"
    delete:
      summary: 删除订单
      description: 删除订单
      tags:
        - "orders"
      responses:
        '200':
          description: OK
